site_url: https://aromaseagles.org
backend:
  name: github
  repo: alxmrs/aromaseagles.org
  branch: main
  base_url: https://auth.merose.com
media_folder: "assets/"
collections:
  - name: "page"
    label: "Page"
    folder: "src/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Description", name: "description-meta", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }